### PR TITLE
Make bootup pin function mapping configurable from boad description

### PR DESCRIPTION
**Pull request by andreas23**
This is so that UARTs other than 0 can be used for console, and other special pin functions, such as USB, can be accessed at boot time.

Also, some whitespace cleanup.

### CODE REVIEW

**Comment by jsnyder** [comment]
Have you tried this on both the xpresso & mbed or does it still need to be tested?

**Comment by andreas23** [comment]
I don't have an MBED to test on, so this is still open. I try to take care not to break anything, of course, and at least the MBED target still builds.

**Comment by andreas23** [comment]
FWIW, the MBED binary still boots up on my LPCXpresso, the LED blinks, and there's output on the pin that's the default uart console on the MBED. Should still be ok, in other words.

**Comment by jsnyder** [comment]
I dug around some bins and found mine, so I'll give it a try.

**Comment by jsnyder** [comment]
Made one minor adjustment for mbed, seems to work with that, merged. Thanks!

**Pull request merged**
