### PR TITLE
Rename linker script for the XMC4500;

### PR DESCRIPTION
**Pull request by ramangopalan**
Support for XMC47 on the way. Prefix family name to the linker_script.

R

### CODE REVIEW

**Comment by bogdanm** [comment]
This PR is weird. github reports "0 files changed" and I don't understand why.

**Comment by ramangopalan** [comment]
Dear Bogdan,

> This PR is weird. github reports "0 files changed" and I don't
> understand why.

Sorry about that. My fault. I tried fetching eLua upstream yesterday
so I can sync my eLua fork. But for some reason I tried to merge it
into my master and invoked a commit instead of a push origin.

I thought I did something silly and reverted the commit. It doesn't
cause a side-effect in the codebase. Just 2 redundant commits. The
main commit is the linker file rename (03595aa). Is there another
way I can fix this OR re-submit the PR?

R

**Comment by bogdanm** [comment]
You can fix the problem on your machine, using whatever dirty git tricks you like :), then push force the changes to this PR. Using push force on a PR is OK in this case. If you don't like that, simply close this one and open another one, that's perfectly fine too.

**Comment by ramangopalan** [comment]
Done Bogdan. Closing it for now. I will initiate another PR. Thanks.

R

**Comment by ramangopalan** [comment]
Sorry. The redundant commits are no more. Bogdan, will this be OK?

**Pull request merged**
