### PR TITLE
Support different clock rates on LPC17xx, don't build mbed specific stuff for lpcxpresso, minor cleanups.

### PR DESCRIPTION
**Pull request by andreas23**
Make clock rate configurable from board description for LPC17xx.

### CODE REVIEW

**Comment by jsnyder** [comment]
Thanks for the patches, Andreas.

I noticed that this also makes the RTC clock configurable. Are there any boards that use an RTC oscillator frequency other than 32.768 kHz?  It looks like the original definition in there is incorrect (32000), but it sounds like the internal RTC circuitry has a fixed divider and that this definition only affects the system clock calculation (quick grep for use of RTC_CLK seems to confirm this):
https://developer.mbed.org/questions/461/mbed-RTC-crystal-frequency-32kHz-or-3276/

Do we need to surface this as a configurable option and if so should it have a default of 32768?

**Comment by andreas23** [comment]
Hi,

I wasn't quite sure about this yesterday, frankly. I originally introduced it because the value for mbed in the code wasn't the same as the one I was seeing for LPCXpresso, then later figured out that the value for mbed was wrong and should be 32768 too. After sleeping over it, I think it's not actually needed, and I will take it out again.

BTW., note that I changed flash access time from 4 to 5, in order to be compliant with the specification when running at the respective clock rates.

**Comment by andreas23** [comment]
Adding some more code to differentiate boards, also made sure Bool looks like on the other platforms.

Is it ok for you to just add to the current pull request, or should I split this stuff up?

**Comment by jsnyder** [comment]
Hi Andreas. This can go in the same pull.  Looks like the pull request can be renamed too.  Just let me know when you've settled this round and I'll take a look over it.

**Comment by andreas23** [comment]
Looks like I'm good for now. I moved to work on USB, which is definitely a separate pull request and will take some time.

**Comment by jsnyder** [comment]
Thanks!  Looking forward to seeing that functionality.

**Pull request merged**
