### PR TITLE
improve shell compatibility with vt100, fix #57

### LINKED ISSUE #57: shell is not compatible with vt100
`"\x1b[0G"` sequence is not supported by vt100
probably it will be better use `"\r"` instead (tested in minicom in Ubuntu)
```
diff --git a/src/linenoise.c b/src/linenoise.c
index fb41583..77c9e1f 100644
--- a/src/linenoise.c
+++ b/src/linenoise.c
@@ -131,7 +131,7 @@ static void refreshLine(const char *prompt, char *buf, size_t len, size_t pos, s
     }
 
     /* Cursor to left edge */
-    snprintf(seq,MAX_SEQ_LEN,"\x1b[0G");
+    snprintf(seq,MAX_SEQ_LEN,"\r");
     term_putstr( seq, strlen( seq ) );
     /* Write the prompt and the current buffer content */
     term_putstr( prompt, strlen( prompt ) );
@@ -140,7 +140,7 @@ static void refreshLine(const char *prompt, char *buf, size_t len, size_t pos, s
     snprintf(seq,MAX_SEQ_LEN,"\x1b[0K");
     term_putstr( seq, strlen( seq ) );
     /* Move cursor to original position. */
-    snprintf(seq,MAX_SEQ_LEN,"\x1b[0G\x1b[%dC", (int)(pos+plen));
+    snprintf(seq,MAX_SEQ_LEN,"\r\x1b[%dC", (int)(pos+plen));
     term_putstr( seq, strlen( seq ) );
 }
```

### PR DESCRIPTION
**Pull request by linvinus**

### CODE REVIEW

**Comment by bogdanm** [comment]
Hi,

I'm OK with the linenoise change, but unfortunately 'shell_vi' relies on a component which is licensed under GPL, so I can't take it in. Sorry about that.

**Comment by linvinus** [comment]
Ok, is it legal if it will be in my repository?

**Comment by bogdanm** [comment]
I'm not 100% sure, so I'll refrain from making any comments in this
direction. At the very least, you should make it clear that your eLua
repository contains a GPL component. Alternatively, if you can put it in a
private repository somewhere for your own use (so you won't redistribute
the code and it won't even be visible to other people), I believe that
would make it legal. In this particular case, could you please remove the
'shell_vi' part from your pull request?

**Comment by gabrield** [comment]
Yes, because you do no retain the author's copyright, you can not  change
the license .
Em 11/03/2015 16:49, "linvinus" <notifications@github.com> escreveu:

**Comment by linvinus** [comment]
i'm sorry, i didn't know that github merges whole trees.
now i'm stuck, looks like there is only one way to merge - undo commits, may be you may apply path by hands? it is trivial. and reject this request.

**Comment by bogdanm** [comment]
Yup, don't worry, I'll do that. Thanks for your help!

**Comment by martinwguy** [comment]
On 11/03/2015, Gabriel Duarte <notifications@github.com> wrote:
> Yes, because you do no retain the author's copyright, you can not  change
> the license .

Hi
https://stackoverflow.com/questions/4035702/can-i-relicense-someones-mit-code-under-gpl
seems to cover it. Short version: yes. Medium version: rewrite the
overall project license as "portions copyright to X".  Elua could do
this if it wanted to - if you compile it without vi you get a MIT
binary; if you include vi you get a GPL binary. However...

There is also xvi https://github.com/martinwguy/xvi which is a full
implementation of vi weighing in at about 100K of compiled code.
However, that too is covered by its own license which basically says
that if you distribute binaries you must tell people where they can
get the corresponding source code, derived from the Emacs license
https://github.com/martinwguy/xvi/blob/master/src/copying
so I guess the same rules apply to that.

    M

We are riding the wavefront of technology
and behind the wavefront is a trough
and the trough is full of lawyers

**Comment by linvinus** [comment]
Thank you for description!
it would be nice if third-party modules could be simple integrated.
i.e. make  folder `/community` from which build system will include modules
it should be simple, in my case (with vi) it will be enough to have macro similar to SHELL_HELP SHELL_INFO, which will include shell commands into SHELL_COMMAND array.

**Pull request closed without merging**
